export const MOVIE_GENRES = [
  { id: '28', name: 'Action' },
  { id: '12', name: 'Adventure' },
  { id: '16', name: 'Animation' },
  { id: '35', name: 'Comedy' },
  { id: '80', name: 'Crime' },
  { id: '99', name: 'Documentary' },
  { id: '18', name: 'Drama' },
  { id: '10751', name: 'Family' },
  { id: '14', name: 'Fantasy' },
  { id: '36', name: 'History' },
  { id: '27', name: 'Horror' },
  { id: '10402', name: 'Music' },
  { id: '9648', name: 'Mystery' },
  { id: '10749', name: 'Romance' },
  { id: '878', name: 'Science Fiction' },
  { id: '10770', name: 'TV Movie' },
  { id: '53', name: 'Thriller' },
  { id: '10752', name: 'War' },
  { id: '37', name: 'Western' }
];

export const TV_GENRES = [
  { id: '10759', name: 'Action & Adventure' },
  { id: '16', name: 'Animation' },
  { id: '35', name: 'Comedy' },
  { id: '80', name: 'Crime' },
  { id: '99', name: 'Documentary' },
  { id: '18', name: 'Drama' },
  { id: '10751', name: 'Family' },
  { id: '10762', name: 'Kids' },
  { id: '9648', name: 'Mystery' },
  { id: '10763', name: 'News' },
  { id: '10764', name: 'Reality' },
  { id: '10765', name: 'Sci-Fi & Fantasy' },
  { id: '10766', name: 'Soap' },
  { id: '10767', name: 'Talk' },
  { id: '10768', name: 'War & Politics' },
  { id: '37', name: 'Western' }
];

export const COUNTRIES = [
  { id: 'AF', name: "Afghanistan" },
  { id: 'AL', name: "Albania" },
  { id: 'DZ', name: "Algeria" },
  { id: 'AS', name: "American Samoa" },
  { id: 'AD', name: "Andorra" },
  { id: 'AO', name: "Angola" },
  { id: 'AI', name: "Anguilla" },
  { id: 'AQ', name: "Antarctica" },
  { id: 'AG', name: "Antigua and Barbuda" },
  { id: 'AR', name: "Argentina" },
  { id: 'AM', name: "Armenia" },
  { id: 'AW', name: "Aruba" },
  { id: 'AU', name: "Australia" },
  { id: 'AT', name: "Austria" },
  { id: 'AZ', name: "Azerbaijan" },
  { id: 'BS', name: "Bahamas" },
  { id: 'BH', name: "Bahrain" },
  { id: 'BD', name: "Bangladesh" },
  { id: 'BB', name: "Barbados" },
  { id: 'BY', name: "Belarus" },
  { id: 'BE', name: "Belgium" },
  { id: 'BZ', name: "Belize" },
  { id: 'BJ', name: "Benin" },
  { id: 'BM', name: "Bermuda" },
  { id: 'BT', name: "Bhutan" },
  { id: 'BO', name: "Bolivia" },
  { id: 'BA', name: "Bosnia and Herzegovina" },
  { id: 'BW', name: "Botswana" },
  { id: 'BV', name: "Bouvet Island" },
  { id: 'BR', name: "Brazil" },
  { id: 'IO', name: "British Indian Ocean Territory" },
  { id: 'VG', name: "British Virgin Islands" },
  { id: 'BN', name: "Brunei Darussalam" },
  { id: 'BG', name: "Bulgaria" },
  { id: 'BF', name: "Burkina Faso" },
  { id: 'BU', name: "Burma" },
  { id: 'BI', name: "Burundi" },
  { id: 'KH', name: "Cambodia" },
  { id: 'CM', name: "Cameroon" },
  { id: 'CA', name: "Canada" },
  { id: 'CV', name: "Cape Verde" },
  { id: 'KY', name: "Cayman Islands" },
  { id: 'CF', name: "Central African Republic" },
  { id: 'TD', name: "Chad" },
  { id: 'CL', name: "Chile" },
  { id: 'CN', name: "China" },
  { id: 'CX', name: "Christmas Island" },
  { id: 'CC', name: "Cocos  Islands" },
  { id: 'CO', name: "Colombia" },
  { id: 'KM', name: "Comoros" },
  { id: 'CD', name: "Congo" },
  { id: 'CG', name: "Congo" },
  { id: 'CK', name: "Cook Islands" },
  { id: 'CR', name: "Costa Rica" },
  { id: 'CI', name: "Cote D'Ivoire" },
  { id: 'HR', name: "Croatia" },
  { id: 'CU', name: "Cuba" },
  { id: 'CY', name: "Cyprus" },
  { id: 'CZ', name: "Czech Republic" },
  { id: 'XC', name: "Czechoslovakia" },
  { id: 'DK', name: "Denmark" },
  { id: 'DJ', name: "Djibouti" },
  { id: 'DM', name: "Dominica" },
  { id: 'DO', name: "Dominican Republic" },
  { id: 'XG', name: "East Germany" },
  { id: 'TP', name: "East Timor" },
  { id: 'EC', name: "Ecuador" },
  { id: 'EG', name: "Egypt" },
  { id: 'SV', name: "El Salvador" },
  { id: 'GQ', name: "Equatorial Guinea" },
  { id: 'ER', name: "Eritrea" },
  { id: 'EE', name: "Estonia" },
  { id: 'ET', name: "Ethiopia" },
  { id: 'FO', name: "Faeroe Islands" },
  { id: 'FK', name: "Falkland Islands" },
  { id: 'FJ', name: "Fiji" },
  { id: 'FI', name: "Finland" },
  { id: 'FR', name: "France" },
  { id: 'GF', name: "French Guiana" },
  { id: 'PF', name: "French Polynesia" },
  { id: 'TF', name: "French Southern Territories" },
  { id: 'GA', name: "Gabon" },
  { id: 'GM', name: "Gambia" },
  { id: 'GE', name: "Georgia" },
  { id: 'DE', name: "Germany" },
  { id: 'GH', name: "Ghana" },
  { id: 'GI', name: "Gibraltar" },
  { id: 'GR', name: "Greece" },
  { id: 'GL', name: "Greenland" },
  { id: 'GD', name: "Grenada" },
  { id: 'GP', name: "Guadaloupe" },
  { id: 'GU', name: "Guam" },
  { id: 'GT', name: "Guatemala" },
  { id: 'GN', name: "Guinea" },
  { id: 'GW', name: "Guinea-Bissau" },
  { id: 'GY', name: "Guyana" },
  { id: 'HT', name: "Haiti" },
  { id: 'HM', name: "Heard and McDonald Islands" },
  { id: 'VA', name: "Holy See" },
  { id: 'HN', name: "Honduras" },
  { id: 'HK', name: "Hong Kong" },
  { id: 'HU', name: "Hungary" },
  { id: 'IS', name: "Iceland" },
  { id: 'IN', name: "India" },
  { id: 'ID', name: "Indonesia" },
  { id: 'IR', name: "Iran" },
  { id: 'IQ', name: "Iraq" },
  { id: 'IE', name: "Ireland" },
  { id: 'IL', name: "Israel" },
  { id: 'IT', name: "Italy" },
  { id: 'JM', name: "Jamaica" },
  { id: 'JP', name: "Japan" },
  { id: 'JO', name: "Jordan" },
  { id: 'KZ', name: "Kazakhstan" },
  { id: 'KE', name: "Kenya" },
  { id: 'KI', name: "Kiribati" },
  { id: 'XK', name: "Kosovo" },
  { id: 'KW', name: "Kuwait" },
  { id: 'KG', name: "Kyrgyz Republic" },
  { id: 'LA', name: "Lao People's Democratic Republic" },
  { id: 'LV', name: "Latvia" },
  { id: 'LB', name: "Lebanon" },
  { id: 'LS', name: "Lesotho" },
  { id: 'LR', name: "Liberia" },
  { id: 'LY', name: "Libyan Arab Jamahiriya" },
  { id: 'LI', name: "Liechtenstein" },
  { id: 'LT', name: "Lithuania" },
  { id: 'LU', name: "Luxembourg" },
  { id: 'MO', name: "Macao" },
  { id: 'MK', name: "Macedonia" },
  { id: 'MG', name: "Madagascar" },
  { id: 'MW', name: "Malawi" },
  { id: 'MY', name: "Malaysia" },
  { id: 'MV', name: "Maldives" },
  { id: 'ML', name: "Mali" },
  { id: 'MT', name: "Malta" },
  { id: 'MH', name: "Marshall Islands" },
  { id: 'MQ', name: "Martinique" },
  { id: 'MR', name: "Mauritania" },
  { id: 'MU', name: "Mauritius" },
  { id: 'YT', name: "Mayotte" },
  { id: 'MX', name: "Mexico" },
  { id: 'FM', name: "Micronesia" },
  { id: 'MD', name: "Moldova" },
  { id: 'MC', name: "Monaco" },
  { id: 'MN', name: "Mongolia" },
  { id: 'ME', name: "Montenegro" },
  { id: 'MS', name: "Montserrat" },
  { id: 'MA', name: "Morocco" },
  { id: 'MZ', name: "Mozambique" },
  { id: 'MM', name: "Myanmar" },
  { id: 'NA', name: "Namibia" },
  { id: 'NR', name: "Nauru" },
  { id: 'NP', name: "Nepal" },
  { id: 'NL', name: "Netherlands" },
  { id: 'AN', name: "Netherlands Antilles" },
  { id: 'NC', name: "New Caledonia" },
  { id: 'NZ', name: "New Zealand" },
  { id: 'NI', name: "Nicaragua" },
  { id: 'NE', name: "Niger" },
  { id: 'NG', name: "Nigeria" },
  { id: 'NU', name: "Niue" },
  { id: 'NF', name: "Norfolk Island" },
  { id: 'KP', name: "North Korea" },
  { id: 'XI', name: "Northern Ireland" },
  { id: 'MP', name: "Northern Mariana Islands" },
  { id: 'NO', name: "Norway" },
  { id: 'OM', name: "Oman" },
  { id: 'PK', name: "Pakistan" },
  { id: 'PW', name: "Palau" },
  { id: 'PS', name: "Palestinian Territory" },
  { id: 'PA', name: "Panama" },
  { id: 'PG', name: "Papua New Guinea" },
  { id: 'PY', name: "Paraguay" },
  { id: 'PE', name: "Peru" },
  { id: 'PH', name: "Philippines" },
  { id: 'PN', name: "Pitcairn Island" },
  { id: 'PL', name: "Poland" },
  { id: 'PT', name: "Portugal" },
  { id: 'PR', name: "Puerto Rico" },
  { id: 'QA', name: "Qatar" },
  { id: 'RE', name: "Reunion" },
  { id: 'RO', name: "Romania" },
  { id: 'RU', name: "Russia" },
  { id: 'RW', name: "Rwanda" },
  { id: 'WS', name: "Samoa" },
  { id: 'SM', name: "San Marino" },
  { id: 'ST', name: "Sao Tome and Principe" },
  { id: 'SA', name: "Saudi Arabia" },
  { id: 'SN', name: "Senegal" },
  { id: 'RS', name: "Serbia" },
  { id: 'CS', name: "Serbia and Montenegro" },
  { id: 'SC', name: "Seychelles" },
  { id: 'SL', name: "Sierra Leone" },
  { id: 'SG', name: "Singapore" },
  { id: 'SK', name: "Slovakia" },
  { id: 'SI', name: "Slovenia" },
  { id: 'SB', name: "Solomon Islands" },
  { id: 'SO', name: "Somalia" },
  { id: 'ZA', name: "South Africa" },
  { id: 'GS', name: "South Georgia and the South Sandwich Islands" },
  { id: 'KR', name: "South Korea" },
  { id: 'SS', name: "South Sudan" },
  { id: 'SU', name: "Soviet Union" },
  { id: 'ES', name: "Spain" },
  { id: 'LK', name: "Sri Lanka" },
  { id: 'SH', name: "St. Helena" },
  { id: 'KN', name: "St. Kitts and Nevis" },
  { id: 'LC', name: "St. Lucia" },
  { id: 'PM', name: "St. Pierre and Miquelon" },
  { id: 'VC', name: "St. Vincent and the Grenadines" },
  { id: 'SD', name: "Sudan" },
  { id: 'SR', name: "Suriname" },
  { id: 'SJ', name: "Svalbard & Jan Mayen Islands" },
  { id: 'SZ', name: "Swaziland" },
  { id: 'SE', name: "Sweden" },
  { id: 'CH', name: "Switzerland" },
  { id: 'SY', name: "Syrian Arab Republic" },
  { id: 'TW', name: "Taiwan" },
  { id: 'TJ', name: "Tajikistan" },
  { id: 'TZ', name: "Tanzania" },
  { id: 'TH', name: "Thailand" },
  { id: 'TL', name: "Timor-Leste" },
  { id: 'TG', name: "Togo" },
  { id: 'TK', name: "Tokelau" },
  { id: 'TO', name: "Tonga" },
  { id: 'TT', name: "Trinidad and Tobago" },
  { id: 'TN', name: "Tunisia" },
  { id: 'TR', name: "Turkey" },
  { id: 'TM', name: "Turkmenistan" },
  { id: 'TC', name: "Turks and Caicos Islands" },
  { id: 'TV', name: "Tuvalu" },
  { id: 'UG', name: "Uganda" },
  { id: 'UA', name: "Ukraine" },
  { id: 'AE', name: "United Arab Emirates" },
  { id: 'GB', name: "United Kingdom" },
  { id: 'US', name: "United States of America" },
  { id: 'UM', name: "United States Minor Outlying Islands" },
  { id: 'UY', name: "Uruguay" },
  { id: 'VI', name: "US Virgin Islands" },
  { id: 'UZ', name: "Uzbekistan" },
  { id: 'VU', name: "Vanuatu" },
  { id: 'VE', name: "Venezuela" },
  { id: 'VN', name: "Vietnam" },
  { id: 'WF', name: "Wallis and Futuna Islands" },
  { id: 'EH', name: "Western Sahara" },
  { id: 'YE', name: "Yemen" },
  { id: 'YU', name: "Yugoslavia" },
  { id: 'ZR', name: "Zaire" },
  { id: 'ZM', name: "Zambia" },
  { id: 'ZW', name: "Zimbabwe" }
];

export const MOVIE_CATEGORIES = [
  { id: 'popular', name: 'Popular' },
  { id: 'now_playing', name: 'Now Playing' },
  { id: 'upcoming', name: 'Upcoming' },
  { id: 'top_rated', name: 'Top Rated' }
];

export const TV_CATEGORIES = [
  { id: 'popular', name: 'Popular' },
  { id: 'airing_today', name: 'Airing Today' },
  { id: 'on_the_air', name: 'On TV' },
  { id: 'top_rated', name: 'Top Rated' }
];

const currentYear = new Date().getFullYear();
export const YEARS = Array.from({ length: 50 }, (_, i) => (currentYear - i).toString());
